server:
  port: 9020
#Eureka
spring.application.name: provider-service
eureka.client.serviceUrl.defaultZone: http://localhost:9010/eureka/

#Hystrix

#LOG
logging:
  level.com: DEBUG
  file: ..\\log\\${spring.application.name}.log